#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTM3NjExNDk3MzhkZGYzNWViODk2ZWY5NjYxNDcyN2ZhOGU2M2U1MDFmYWY5MDZjODdhYzRjNDNlOWQ4YzZjMDdhYjQ0ZmY1ZmUxMjIwZTY4MDg1ZmQyZWRlZjJkZmViNWM5Nw==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
