export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  DIRETOR = 'ROLE_DIRETOR',
  RESPONSAVEL_CENTRAL_COMANDOS = 'ROLE_RESPONSAVEL_CENTRAL_COMANDOS',
  RESPONSAVEL_SEGURANCA = 'ROLE_RESPONSAVEL_SEGURANCA',
  GUARDA_PRISIONAL = 'ROLE_GUARDA_PRISIONAL',
  RECLUSO = 'ROLE_RECLUSO',
  TECNICO = 'ROLE_TECNICO'
}
